const mysql = require("mysql2/promise");

// Complete translation map for all Chinese text in task content
const map = {
  // === P-Stage Subtask Titles ===
  "获取变量": "Get Variable",
  "条件判断": "Conditional Check",
  "输出结果": "Output Result",
  "创建变量": "Create Variable",
  "循环结构": "Loop Structure",
  "变量更新": "Variable Update", 
  "获取输入": "Get Input",
  "拼接文本": "Join Text",
  "长度判断": "Length Check",
  "循环遍历": "Loop Iteration",
  "奇偶判断": "Even/Odd Check",
  "统计计数": "Counting",

  // === P-Stage Block Types ===
  "变量赋值": "Variable Assignment",
  "if-else 判断": "if-else Statement",
  "比较运算": "Comparison",
  "print 输出": "Print Output",
  "重复N次": "Repeat N Times",
  "变量更新（n=n-1)": "Update Variable (n=n-1)",
  "减法运算": "Subtraction",
  "询问并等待": "Ask and Wait",
  "文本拼接": "Text Join",
  "字符串长度": "String Length",
  "取得余数": "Modulo",

  // === P-Stage Explanations ===
  "创建一个变量score，把85存进去。": "Create a variable called score and store 85 in it.",
  "if 后面跟条件，条件成立执行 if 里的代码。注意冒号和缩进。": "if is followed by a condition. If true, the code inside if runs. Mind the colon and indentation.",
  ">= 表示大于或等于。比较结果要么 True 要么 False。": ">= means greater than or equal. The result is either True or False.",
  "print() 把内容显示到屏幕上。": "print() displays content on the screen.",
  "创建一个变量n，把5存进去。": "Create a variable n and store 5 in it.",
  "for 循环让代码重复执行。range(5) 表示执行5次。": "for loop repeats code execution. range(5) means 5 iterations.",
  "输出当前n的值到屏幕。": "Print the current value of n to the screen.",
  "把n减1后存回n中，实现倒数。": "Subtract 1 from n and store it back, creating a countdown.",
  "input() 让程序停下来等待用户输入，提示文字写在括号里。": "input() pauses the program to wait for user input. The prompt text goes in parentheses.",
  "把用户输入的内容存到变量name里。": "Store the user's input in the variable name.",
  "用+把'你好，'和name拼接起来。": "Use + to join 'Hello, ' and name together.",
  "把拼接后的结果输出到屏幕上。": "Output the joined result to the screen.",
  "len() 计算字符串的长度（有几个字）。": "len() calculates the length of a string (how many characters).",
  "> 表示大于。比较结果要么 True 要么 False。": "> means greater than. Result is True or False.",
  "for 循环让i从0到9，共10次。": "for loop makes i go from 0 to 9, 10 times total.",
  "% 是取余运算——判断一个数除以另一个数的余数。": "% is the modulo operator — finds the remainder of division.",
  "if 后面跟条件，条件成立执行 if 里的代码块。": "if is followed by a condition. When true, the code block inside if runs.",
  "每次遇到偶数，count加1。": "Each time an even number is found, increment count by 1.",

  // === Python code strings in P-stage blocks ===
  "print('及格')": "print('Pass')",
  "print('不及格')": "print('Fail')",
  "print('优秀')": "print('Excellent')",
  "print(n)": "print(n)",
  "print('偶')": "print('Even')",
  "print('奇')": "print('Odd')",
  "print('你好，' + name)": 'print("Hello, " + name)',
  "print('名字很长')": "print('Long name')",
  "print('名字很短')": "print('Short name')",
  "print(count)": "print(count)",
};

function translate(str) {
  if (!str || typeof str !== "string") return str;
  let result = str;
  for (const [cn, en] of Object.entries(map)) {
    result = result.split(cn).join(en);
  }
  return result;
}

function deepTranslate(obj) {
  if (typeof obj === "string") return translate(obj);
  if (Array.isArray(obj)) return obj.map(deepTranslate);
  if (obj && typeof obj === "object") {
    const result = {};
    for (const [k, v] of Object.entries(obj)) {
      // Don't translate blocks_xml (LLM generates it in English)
      if (k === "blocks_xml") { result[k] = v; continue; }
      result[k] = deepTranslate(v);
    }
    return result;
  }
  return obj;
}

async function main() {
  const cnPool = mysql.createPool({ host: "localhost", port: 3306, user: "root", password: "123456", database: "icap_platform" });
  const enPool = mysql.createPool({ host: "localhost", port: 3306, user: "root", password: "123456", database: "icap_platform_english" });

  const [cnRows] = await cnPool.query("SELECT id, content_json FROM tasks ORDER BY id");
  const [enRows] = await enPool.query("SELECT id, content_json FROM tasks ORDER BY id");

  for (const cnRow of cnRows) {
    const enId = cnRow.id - 6;
    const enRow = enRows.find(r => r.id === enId);
    if (!enRow) continue;

    const enContent = enRow.content_json;
    
    // Only translate p_stage from Chinese source
    if (cnRow.content_json.p_stage) {
      enContent.p_stage = deepTranslate(JSON.parse(JSON.stringify(cnRow.content_json.p_stage)));
    }
    // Also fix blocks_xml if it contains Chinese
    if (enContent.c_stage?.blocks_xml && /[\u4e00-\u9fff]/.test(enContent.c_stage.blocks_xml)) {
      // Regenerate by clearing (will be auto-generated by LLM on next load)
      enContent.c_stage.blocks_xml = undefined;
    }
    
    await enPool.query("UPDATE tasks SET content_json = ? WHERE id = ?", [JSON.stringify(enContent), enId]);
    console.log(`Task ${enId}: p_stage translated`);
  }

  await cnPool.end();
  await enPool.end();
  console.log("Complete!");
}

main().catch(console.error);
